apiVersion : apps/v1
kind: Deployment
metadata:
  name: matthiasmansoftdeplgroupworkhellowexpress 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matthiasmansoftdeplgroupworkhellowexpress
  template:
    metadata:
      labels:
        app: matthiasmansoftdeplgroupworkhellowexpress 
    spec:
      containers:
        - name: matthiasmansoftdeplgroupworkhellowexpress 
          image: groupworkregistry.azurecr.io/matthiasmansoftdeplgroupworkhellowexpress
          ports:
          - containerPort: 3000