apiVersion: v1
kind: Service
metadata:
    name: matthiasmansoftdeplgroupwork
spec:
    type: LoadBalancer
    ports:
    - port: 3000 
    selector:
        app: matthiasmansoftdeplgroupwork